language: node_js
node_js:
  - '0.10'
before_install:
  - npm install -g npm
  - npm install -g bower
  - bower install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run test-once
after_script:
  - cat ./coverage/PhantomJS*/lcov.info | ./node_modules/codeclimate-test-reporter/bin/codeclimate.js
after_success:
  -npm install -g firebase-tools
  -if [[ "$TRAVIS_PULL_REQUEST" == "false"]] && [[ "$TRAVIS_BRANCH" == "master" ]]; then npm run deploy; fi
env:
  global:
    - secure: Toh/McRUfeHpoewhP92DMtLgFZ0v+hawt/DQ5PA/TTCAbaZ0JX5MvPKQUB5S9PHpyDomANaFWtnJKtzDpKEp7QHq+RvXLcIof0yW9DXY4myJe0VvnW8zL9Y16xhAUBzQFqwsOF7YIKVCDK20+hBmhj2FDp259fpOD155Q42PhuM=
    - secure: gtnhquaOdAXQWOUTNLtBp7S6b4Qts76uSflWIuJpnmwlT6zUNqmKyZPQi4IN8HWm1fE5D40PtVsucbqzuYfgPe3UxnhMCR8k5FHW4KPU00nl0WKn6+TY4c03/Z2t8Lc/BPK1msef3k/18iXPVDL4GXiFhQq5rGBKj+EgN113LcM=
    - secure: Oshl3HQu8Eme52cQ3AkohYFyvYZaXjxdLoXpzGg16rh3BxNPx8Y+m56L1SCe12Gsi60+8CV1vR86GexESxURcjkfBZQmx2poFO/PpXKKrypDxh5BQcZ4+2D2PxQ0o1CybGXNMOO/ay7MPiZwAqgZdYTlmD/cZPVOyHMoevSw2Mk=
    - secure: hjKpiiP3W07hbSw731XDIJnNXzw9wDkn3h3DDOgCH38ls7V5J0lo8KyQS05sceJRkvjruNSrAVxqUy+H4twsiGFgVS0WavLNujJJ5WMMJIgRlCWc/TPPcMjoWiFP+BH6PgMxMLn8zvvXd99teUNnYPCnMw5P5hfYbOdppBlPzwE=
